services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ciso_assistant
      POSTGRES_USER: ciso_assistant
      POSTGRES_PASSWORD: ciso_assistant
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ciso_assistant"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: ciso_assistant.settings
      DJANGO_DEBUG: "False"
      ALLOWED_HOSTS: "grc-client1.completecyber.uk,*.dokploy.com"
      CISO_ASSISTANT_URL: https://grc-client1.completecyber.uk
      POSTGRES_NAME: ciso_assistant
      POSTGRES_USER: ciso_assistant
      POSTGRES_PASSWORD: ciso_assistant
      DB_HOST: db
      DB_PORT: 5432
      # SMTP Configuration for email functionality
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_HOST_USER: ejones@completecyber.uk
      EMAIL_HOST_PASSWORD: vwrahbxebhmrzidy
      EMAIL_USE_TLS: "True"
      DEFAULT_FROM_EMAIL: ejones@completecyber.uk
      # Optional: create an admin on first boot
      # DJANGO_SUPERUSER_EMAIL: admin@example.com
      # DJANGO_SUPERUSER_PASSWORD: change-me
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app/backend/db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PUBLIC_BACKEND_API_URL: http://backend:8000/api
      PORT: 8080
      HOST: 0.0.0.0
    depends_on:
      - backend
    # ports:
    #   - "3000:8080"
    # networks:
    #   - dokploy-network
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.ccyber-frontend.rule=Host(`grc-client1.completecyber.uk`)"
    #   - "traefik.http.routers.ccyber-frontend.entrypoints=websecure"
    #   - "traefik.http.routers.ccyber-frontend.tls.certResolver=letsencrypt"
    #   - "traefik.http.services.ccyber-frontend.loadbalancer.server.port=8080"

  huey:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -lc "poetry run python manage.py run_huey -w 2 -k process"
    environment:
      DJANGO_SETTINGS_MODULE: ciso_assistant.settings
      DJANGO_DEBUG: "False"
      ALLOWED_HOSTS: "grc-client1.completecyber.uk,*.dokploy.com"
      CISO_ASSISTANT_URL: https://grc-client1.completecyber.uk
      POSTGRES_NAME: ciso_assistant
      POSTGRES_USER: ciso_assistant
      POSTGRES_PASSWORD: ciso_assistant
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started
    volumes:
      - backend_data:/app/backend/db

volumes:
  db_data:
  backend_data: