services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ciso_assistant_client2
      POSTGRES_USER: ciso_assistant_client2
      POSTGRES_PASSWORD: ciso_assistant_client2_secure_password
    volumes:
      - db_data_client2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ciso_assistant_client2"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    image: ghcr.io/rishiiii9/complete-cyber-backend:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: ciso_assistant.settings
      DJANGO_DEBUG: "False"
      ALLOWED_HOSTS: "grc-client2.completecyber.uk,*.dokploy.com"
      CISO_ASSISTANT_URL: https://grc-client2.completecyber.uk
      POSTGRES_NAME: ciso_assistant_client2
      POSTGRES_USER: ciso_assistant_client2
      POSTGRES_PASSWORD: ciso_assistant_client2_secure_password
      DB_HOST: db
      DB_PORT: 5432
      # SMTP Configuration for email functionality
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_HOST_USER: ejones@completecyber.uk
      EMAIL_HOST_PASSWORD: vwrahbxebhmrzidy
      EMAIL_USE_TLS: "True"
      DEFAULT_FROM_EMAIL: ejones@completecyber.uk
      # Client-specific admin user
      DJANGO_SUPERUSER_EMAIL: admin@grc-client2.completecyber.uk
      DJANGO_SUPERUSER_PASSWORD: admin_client2_secure_password
    ports:
      - "8000:8000"
    volumes:
      - backend_data_client2:/app/backend/db

  frontend:
    image: ghcr.io/rishiiii9/complete-cyber-frontend:latest
    environment:
      NODE_ENV: production
      PUBLIC_BACKEND_API_URL: http://backend:8000/api
      PORT: 3000
      HOST: 0.0.0.0
    depends_on:
      - backend
    ports:
      - "3000:3000"

  huey:
    image: ghcr.io/rishiiii9/complete-cyber-backend:latest
    command: bash -lc "poetry run python manage.py run_huey -w 2 -k process"
    environment:
      DJANGO_SETTINGS_MODULE: ciso_assistant.settings
      DJANGO_DEBUG: "False"
      ALLOWED_HOSTS: "grc-client2.completecyber.uk,*.dokploy.com"
      CISO_ASSISTANT_URL: https://grc-client2.completecyber.uk
      POSTGRES_NAME: ciso_assistant_client2
      POSTGRES_USER: ciso_assistant_client2
      POSTGRES_PASSWORD: ciso_assistant_client2_secure_password
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started
    volumes:
      - backend_data_client2:/app/backend/db

volumes:
  db_data_client2:
  backend_data_client2:
