services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ciso_assistant
      POSTGRES_USER: ciso_assistant
      POSTGRES_PASSWORD: ciso_assistant
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ciso_assistant"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: ciso_assistant.settings
      DJANGO_DEBUG: "False"
      ALLOWED_HOSTS: "*"
      CISO_ASSISTANT_URL: https://ccyber.traefik.me
      POSTGRES_NAME: ciso_assistant
      POSTGRES_USER: ciso_assistant
      POSTGRES_PASSWORD: ciso_assistant
      DB_HOST: db
      DB_PORT: 5432
      # Optional: create an admin on first boot
      # DJANGO_SUPERUSER_EMAIL: admin@example.com
      # DJANGO_SUPERUSER_PASSWORD: change-me
    ports:
      - "8000:8000"
    networks:
      - dokploy-network
    volumes:
      - backend_data:/app/backend/db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PUBLIC_BACKEND_API_URL: http://backend:8000/api
      PORT: 8080
      HOST: 0.0.0.0
    depends_on:
      - backend
    ports:
      - "4000:8080"
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.<unique-name>.rule=Host(`ccyber.traefik.me`)"
      - "traefik.http.routers.<unique-name>.entrypoints=websecure"
      - "traefik.http.routers.<unique-name>.tls.certResolver=letsencrypt"
      - "traefik.http.services.<unique-name>.loadbalancer.server.port=4000"

  huey:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -lc "poetry run python manage.py run_huey -w 2 -k process"
    environment:
      DJANGO_SETTINGS_MODULE: ciso_assistant.settings
      DJANGO_DEBUG: "False"
      ALLOWED_HOSTS: "*"
      CISO_ASSISTANT_URL: https://ccyber.traefik.me
      POSTGRES_NAME: ciso_assistant
      POSTGRES_USER: ciso_assistant
      POSTGRES_PASSWORD: ciso_assistant
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started
    volumes:
      - backend_data:/app/backend/db
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true
volumes:
  db_data:
  backend_data: